---
- name: Create Directory
  file:
    path: /tmp/{{ cluster_fqdn }}/platform/metallb
    state: directory

- name: Template Files
  template:
    src: configmap.j2
    dest: /tmp/{{ cluster_fqdn }}/platform/metallb/configmap.yaml

- name: Copy Files
  copy:
    src: "{{ item.name }}"
    dest: /tmp/{{ cluster_fqdn }}/platform/metallb/{{ item.dest | default(item.name) }}
  when: item.condition | default(true)
  loop:
    - name: ns.yaml
    - name: metallb.yaml
    - name: kustomization.yaml 

- name: Apply Resources
  tags: [ requires_cluster ]
  when: ('dry-run' not in ansible_run_tags)
  loop: "{{ lookup('ms3_inc.tavros.kustomize', '/tmp/' + cluster_fqdn + '/platform/metallb/', reorder='none') }}"
  loop_control:
    label: "{{ item.kind }}/{{ item.metadata.name | default('unnamed')}}"
  ms3_inc.tavros.kube:
    kubeconfig: '~/.kube/config'
    definition: "{{ item }}"
    wait: true
    wait_condition: "{{ wait_conditions[item.kind] | default(omit) }}"
    wait_timeout: 900
  retries: 2
  delay: 3
  register: result
  until: result is succeeded
