apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - csi-nfs-controller.yaml
  - csi-nfs-driverinfo.yaml
  - csi-nfs-node.yaml
  - rbac-csi-nfs-controller.yaml
  - nfs-sc.yaml
